### ISSUE TITLE
Candidates List with multiple events

### ISSUE THREAD

**Issue by thesps** [ashtipliyski/threejs-visualiser#20]
When using the web app, and loading a json file with multiple events I see a bug when changing event.
After clicking 'next event' or 'previous event', the event's candidates seem to be appended to the list of candidates, rather than replacing the current list. See an example in the attached file where the candidate number rolls over from 230 (candidate 230 from event 1) to 1 (candidate 1 from event 2).
![multieventbug](https://cloud.githubusercontent.com/assets/14807534/13425278/a26dc2d2-df9d-11e5-9e91-cd5a9e537bfb.png)

**Comment by ashtipliyski** [comment]
Hi Sioni,

Thanks for pointing this out, it has been fixed in d1be253d664d038c4882825a1e761ca54604900d and you should be able to see the changes in the live site. I believe the issue was only limited to the data table but let me know if you find indications that it was more widespread.

Thanks,
Antoni
